import { initMidnightNetwork, buildMidnightProviders, deployAdContract } from '@admidnight/midnight-sdk-wrapper';
import { writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const MANAGED_DIR = resolve(__dirname, '..', 'managed');

const networkId = (process.env.MIDNIGHT_NETWORK_ID ?? 'undeployed') as
  | 'undeployed'
  | 'devnet'
  | 'testnet'
  | 'mainnet';

initMidnightNetwork(networkId);

const password = process.env.MIDNIGHT_PRIVATE_STATE_PASSWORD ?? '';
if (password.length < 16) {
  console.error('ERROR: MIDNIGHT_PRIVATE_STATE_PASSWORD must be ≥16 chars');
  process.exit(1);
}

console.log(`[Deploy] Network: ${networkId}`);

const providers = await buildMidnightProviders({
  networkId,
  indexerGraphQlUrl: process.env.MIDNIGHT_INDEXER_GRAPHQL_URL ?? 'http://localhost:6400/graphql',
  indexerWsUrl: process.env.MIDNIGHT_INDEXER_WS_URL ?? 'ws://localhost:6400/graphql',
  proofServerUrl: process.env.MIDNIGHT_PROOF_SERVER_URL ?? 'http://localhost:6300',
  zkArtifactsDir: MANAGED_DIR,
  privateStateStoreName: 'admidnight-deployer',
  privateStatePassword: password,
  accountId: 'deployer',
});

console.log('[Deploy] Deploying AdMatchRegistry...');
const matchRegistry = await deployAdContract(providers, {
  compiledContractModule: `${MANAGED_DIR}/AdMatchRegistry/index.js`,
  privateStateId: 'match-registry-init',
  initialPrivateState: {},
});
console.log(`[Deploy] ✓ AdMatchRegistry: ${matchRegistry.address}`);

console.log('[Deploy] Deploying AdAuction...');
const adAuction = await deployAdContract(providers, {
  compiledContractModule: `${MANAGED_DIR}/AdAuction/index.js`,
  privateStateId: 'auction-init',
  initialPrivateState: {},
});
console.log(`[Deploy] ✓ AdAuction: ${adAuction.address}`);

console.log('[Deploy] Deploying UserReward...');
const userReward = await deployAdContract(providers, {
  compiledContractModule: `${MANAGED_DIR}/UserReward/index.js`,
  privateStateId: 'reward-init',
  initialPrivateState: {},
});
console.log(`[Deploy] ✓ UserReward: ${userReward.address}`);

const envContent = [
  `# Generated by deploy.mts at ${new Date().toISOString()}`,
  `MATCH_REGISTRY_CONTRACT_ADDRESS=${matchRegistry.address}`,
  `AUCTION_CONTRACT_ADDRESS=${adAuction.address}`,
  `REWARD_CONTRACT_ADDRESS=${userReward.address}`,
].join('\n');

writeFileSync(resolve(__dirname, '..', '.env.contracts'), envContent);

console.log('[Deploy] Contract addresses written to packages/zk-circuits/.env.contracts');
console.log('[Deploy] Copy these values into your root .env file.');
